### ISSUE TITLE
403 Error

### ISSUE THREAD

**Issue by MartinStamenkovski** [get-pytube/pytube3#76]
I posted this in pytube but I figured that this should be here also, because it’s the same result.

The video streams that are extracted are only working from the IP where the extraction happened.

For example if you extract the content on server and want to use it somewhere else, the streams are not accessible.

Any solution ?

**Comment by wes1993** [comment]
> I posted this in pytube but I figured that this should be here also, because it’s the same result.
> 
> The video streams that are extracted are only working from the IP where the extraction happened.
> 
> For example if you extract the content on server and want to use it somewhere else, the streams are not accessible.
> 
> Any solution ?

Hello, i have the same problem, have you found a solution?
Best regards
Stefano

**Comment by MartinStamenkovski** [comment]
Unfortunately no, so I'm just gonna close the issue anyway.
