### ISSUE TITLE
pytubeX is the new pytube3

### ISSUE THREAD

**Issue by H4KKR** [get-pytube/pytube3#99]
The devs on this library have left an easy-to-fix bug for months. So I've claimed the library, and fixed the bugs. 

See https://github.com/H4KKR/pytubeX for the code, and run `pip install pytubeX` to use the library.

All devs of pytube3, when/if they come back, are welcome to contribute to my code. And any help to my code is much appreciated, as this is a massive project!

**Comment by partriv** [comment]
@H4KKR can you take a look at this issue and add fix to pytubex? https://github.com/nficano/pytube/issues/695

**Comment by H4KKR** [comment]
@partriv yes, will do!

**Comment by partriv** [comment]
@H4KKR sick thank you! just got latest pytubex, working great.
